# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171205_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Web\u5b89\u5168', max_length=16, verbose_name='\u83dc\u5355\u540d\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Menus', verbose_name='\u83dc\u5355'),
            preserve_default=False,
        ),
    ]
