# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171205_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
    ]
