# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171205_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descript',
            field=models.CharField(default='', max_length=16, verbose_name='\u63cf\u8ff0'),
        ),
    ]
