# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_menu_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='href_name',
            field=models.CharField(default='', max_length=16, verbose_name='\u94fe\u63a5'),
        ),
    ]
