# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_menu_href_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u4e00\u7ea7\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=16, verbose_name='\u76ee\u5f55\u540d\u79f0'),
        ),
    ]
